
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: kube-system
spec:
  ports:
    - name: webhook-server
      port: 443
      protocol: TCP
      targetPort: 9876 
  selector:
    control-plane: yurt-app-manager
